#!/usr/bin/env bash
# PreToolUse / Bash hook: enforce DCO sign-off on git commits and reject
# forbidden AI-attribution trailers per AGENTS.md "Pull Request Authoring".
#
# Input  : Claude Code hook JSON on stdin (tool_input.command).
# Output : exit 0 to allow; exit 2 + stderr to block.
#
# Only inspects `git commit` invocations; passes through everything else.

set -u

# Read the full stdin JSON; fall back to empty if no jq available.
payload="$(cat || true)"

# Extract the bash command. Prefer jq; fall back to a simple grep.
if command -v jq >/dev/null 2>&1; then
  cmd="$(printf '%s' "$payload" | jq -r '.tool_input.command // ""')"
else
  cmd="$(printf '%s' "$payload" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\(.*\)".*/\1/p' | head -n1)"
fi

# Pass through anything that isn't a git commit.
case "$cmd" in
  *"git commit"*) ;;
  *) exit 0 ;;
esac

# Skip amend-only / rebase-internal flows that don't introduce new messages.
case "$cmd" in
  *"--no-edit"*) exit 0 ;;
esac

# Extract the message if -m / --message is present.
msg=""
if printf '%s' "$cmd" | grep -qE -- "-m[[:space:]]|--message[[:space:]]|-m=|--message="; then
  # Best-effort: grab everything after the first -m up to end-of-line.
  msg="$(printf '%s' "$cmd" | sed -E 's/.*(-m|--message)[[:space:]=]+//; s/[[:space:]]+--?[a-zA-Z].*$//')"
fi

# Require -s / --signoff OR an existing Signed-off-by trailer in the message.
has_signoff_flag=false
case "$cmd" in
  *" -s "*|*" -s"|*" --signoff "*|*" --signoff"|*"-sm "*|*"-ms "*) has_signoff_flag=true ;;
esac
has_signoff_trailer=false
if printf '%s' "$msg" | grep -qE '^[[:space:]]*Signed-off-by:[[:space:]]+.+<.+@.+>'; then
  has_signoff_trailer=true
fi

if [ "$has_signoff_flag" != true ] && [ "$has_signoff_trailer" != true ]; then
  echo "[check-dco] Refusing 'git commit' without DCO sign-off." >&2
  echo "[check-dco] Add -s (or include a 'Signed-off-by:' trailer) per AGENTS.md." >&2
  exit 2
fi

# Reject forbidden AI-attribution trailers (case-insensitive).
forbidden_re='(Co-Authored-By:[[:space:]]*(Claude|Copilot|ChatGPT|GPT)|Generated with \[?Claude Code|🤖 Generated with|Generated by (Claude|Copilot|ChatGPT))'
if printf '%s' "$msg" | grep -qiE "$forbidden_re"; then
  echo "[check-dco] Refusing commit: AI-attribution trailer detected." >&2
  echo "[check-dco] AGENTS.md forbids AI co-author trailers and generation banners in commit messages." >&2
  exit 2
fi

exit 0
