#!/usr/bin/env bash
# PreToolUse / Bash hook: enforce DCO sign-off on git commits and reject
# forbidden AI-attribution trailers per AGENTS.md "Pull Request Authoring".
#
# Input  : Claude Code hook JSON on stdin (tool_input.command).
# Output : exit 0 to allow; exit 2 + stderr to block.
#
# Only inspects `git commit` invocations; passes through everything else.

# Strict mode: -e exits on command failure, -u on unset vars, -o pipefail
# propagates non-zero exits through pipelines so JSON-parsing or sed pipelines
# don't fail silently.
set -euo pipefail

# Read the full stdin JSON.
payload="$(cat || true)"

# Extract the bash command. Prefer jq for robust JSON parsing of the Claude
# Code hook envelope. The sed fallback below is best-effort: it cannot fully
# handle escaped quotes, embedded newlines, or other JSON escapes inside
# .tool_input.command. Install jq for accurate parsing —
# `brew install jq` / `apt install jq`.
if command -v jq >/dev/null 2>&1; then
  # Fail-closed: if jq cannot parse the payload (malformed JSON, truncated
  # input, encoding issues), block the operation rather than passing through
  # with an empty cmd (which would silently allow every dangerous command).
  if ! cmd="$(printf '%s' "$payload" | jq -r '.tool_input.command // ""' 2>/dev/null)"; then
    echo "[check-dco] ERROR: jq failed to parse hook payload — blocking." >&2
    exit 2
  fi
else
  echo "[check-dco] warning: jq not found; using best-effort sed fallback (escaped quotes may be mis-parsed)" >&2
  # Match the first "command":"..." value, stopping at the first unescaped
  # double quote (character class [^"]*). Escaped quotes inside the value
  # WILL truncate the match — accept that and rely on jq for correctness.
  cmd="$(printf '%s' "$payload" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)"
fi

# Pass through anything that isn't a `git commit` invocation. Token-boundary
# match so other subcommands like `git commit-tree` / `git commit-graph` are
# not falsely treated as commits.
if ! printf '%s' "$cmd" | grep -qE '(^|[[:space:]])git[[:space:]]+commit([[:space:]]|$)'; then
  exit 0
fi

# Skip amend-only / rebase-internal flows that don't introduce new messages.
case "$cmd" in
  *"--no-edit"*) exit 0 ;;
esac

# Detect a sign-off flag: -s, --signoff, or any short-flag bundle containing
# 's' (e.g. -s, -sm, -ms, -sa, -vs). Only standalone flags are matched —
# whitespace boundaries on both sides — so substrings like `--option-sm`
# or `--my-signoff-thing` don't false-positive. We're already gated to
# `git commit` invocations above, so any short bundle with 's' is meaningful.
has_signoff_flag=false
if printf '%s' "$cmd" | grep -qE '(^|[[:space:]])(-[a-zA-Z]*s[a-zA-Z]*|--signoff)([[:space:]]|$)'; then
  has_signoff_flag=true
fi

# Detect a Signed-off-by: trailer anywhere in the command string. We scan the
# whole $cmd rather than trying to extract the -m/--message body — that
# extraction was brittle for HEREDOCs and multi-line quoted messages.
has_signoff_trailer=false
if printf '%s' "$cmd" | grep -qE 'Signed-off-by:[[:space:]]+.+<.+@.+>'; then
  has_signoff_trailer=true
fi

if [ "$has_signoff_flag" != true ] && [ "$has_signoff_trailer" != true ]; then
  echo "[check-dco] Refusing 'git commit' without DCO sign-off." >&2
  echo "[check-dco] Add -s (or include a 'Signed-off-by:' trailer) per AGENTS.md." >&2
  exit 2
fi

# Reject forbidden AI-attribution trailers (case-insensitive). Scan the whole
# $cmd — not a parsed message body — so HEREDOCs (`-m "$(cat <<'EOF'...EOF)"`)
# and multi-line quoted messages cannot bypass the check.
forbidden_re='(Co-Authored-By:[[:space:]]*(Claude|Copilot|ChatGPT|GPT)|Generated with \[?Claude Code|🤖 Generated with|Generated by (Claude|Copilot|ChatGPT))'
if printf '%s' "$cmd" | grep -qiE "$forbidden_re"; then
  echo "[check-dco] Refusing commit: AI-attribution trailer detected." >&2
  echo "[check-dco] AGENTS.md forbids AI co-author trailers and generation banners in commit messages." >&2
  exit 2
fi

exit 0
